language: ruby
rvm:
  - jruby
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - jruby-9.0.5.0
  - jruby-9.1.7.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
sudo: false
cache: bundler
before_script:
  - "bundle update"
script: bundle exec rspec spec
addons:
    code_climate:
        repo_token: 003492f2f00fb5d11e9cf945c5d88e44413800190183ee4fa0c97edff4fd553c
