language: ruby
rvm:
  - rbx-2.5.8
  - jruby
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
sudo: false
cache: bundler
before_script:
  - "bundle update"
script: bundle exec rspec spec
